version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - "./files/templates/:/etc/nginx/conf.d/templates/:Z"
      - "../src/output/:/srv/sharij.info/www:Z"
    environment:
      - NGINX_HOST=sharij.info
      - NGINX_PORT=80
      - NGINX_PORT_SSL=443
      - S=$$
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/templates/$$NGINX_HOST.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  pelican:
    build:
      context: ./build/pelican/
    volumes:
      - "../src/:/srv/site/:Z"
    environment:
      - BLOG_THEME_NAME=bold
    command: /bin/bash -c "cd /srv/site/; pelican content -D -r"
#    command: /bin/bash -c "cd /srv/site/; pelican content -t /srv/site/pelican-themes/$$BLOG_THEME_NAME/ -D -r"
    #NEWSITE# command: /bin/bash -c 'cd /srv/site/; pelican-quickstart'

#bold lazystrap monospace
#pelican content -t /srv/pelican-themes/bold/

