version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - "/root/git/srv-nix.com/docker/files/srv-nix.com.template:/etc/nginx/conf.d/srv-nix.com.template:Z"
      - "/root/git/srv-nix.com/src/output/:/srv/srv-nix.com/www:Z"
    environment:
      - NGINX_HOST=srv-nix.com
      - NGINX_PORT=80
      - NGINX_PORT_SSL=443
      - S=$$
    ports:
      - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/srv-nix.com.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  pelican:
    image: pelican:latest
    volumes:
      - "/root/git/srv-nix.com/docker/files/pelicanconf.py:/srv/pelicanconf.py:Z"
      - "/root/git/srv-nix.com/src/:/srv/site/:Z"
    command: /bin/bash -c 'cd /srv/site/; pelican content -t /srv/site/pelican-themes/bold/ -D -r'
    #NEWSITE# command: /bin/bash -c 'cd /srv/site/; pelican-quickstart'

#bold lazystrap monospace
#pelican content -t /srv/pelican-themes/bold/

