name:         SRV-NIX.COM
markdown:     redcarpet
highlighter:  pygments
#highlighter:  rouge
destination:  ./www
source:       .
exclude:      [ 'commit.sh', 'scripts', 'README.md', 'Gemfile' ]
timezone:     Europe/Yekaterinburg
url:          http://srv-nix.com
static:       http://static.srv-nix.com
comments:     yes
gems:         [jekyll-paginate]

gray_message: 'srv-nix.com'

paginate:     77

excerpt_separator: <!--more-->

tag_page_layout:  tag_page
tag_page_dir:     tags

rss_path: /
rss_name: rss.xml
rss_post_limit: 50

sitemap:
  file: "/sitemap.xml"
  exclude:
    - '/hidden/2014-01-01-default.html'
    - '/hidden/feed.html'
    - '/tags.html'
    - '/ts3.html'
    - 'draft'
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

